// config/imgExceptions.excel.js
// Auto-generated from 'Copy of Cards DB.xlsx' (Exceptions columns).
// Map: oshiId -> array of allowed card-name prefixes for /img (change-img.js).
module.exports = {
  "achan": ["Support"],
  "michiru": ["Support"],
  "sayaka": ["Support"],
  "yuki": ["Support"],
  "yagoo": ["Support"],
  "aki": ["Gen 1"],
  "anya": ["holoro", "HoloIndonesia"],
  "ao": ["ReGLOSS"],
  "aqua":["StartEnd", "ManjiGumi"],
  "ayame": ["AyaFubuMi", "Gen 2", "ManjiGumi"],
  "azki": ["Easter X", "Gen 0", "Kanata Construction", "SorAZ", "AS_tar"],
  "baelz": ["Promise", "preYdator"],
  "bijou": ["Advent"],
  "botan": ["NePoLaBo"],
  "cecilia": ["Justice"],
  "chihaya": ["FLOW GLOW"],
  "chloe": ["holoWitches", "holoX", "Kanata Construction", "Padoru Chloe", "Ruka"],
  "choco": ["Gen 2"],
  "elizabeth": ["Justice"],
  "fauna": ["Council", "Promise", "FauMei"],
  "flare": ["BAKATARE CIRCUS", "Fantasy", "MariFure", "Padoru Flare", "Shiranui Construction"],
  "fubuki": ["AyaFubuMi", "BAKATARE CIRCUS", "Dorobo Construction", "FubuMio", "GAMERS", "Gen 1", "FubuMiComet"],
  "fuwawa": ["Advent", "FUWAMOCO"],
  "gigi": ["Justice"],
  "gura": ["Saba"],
  "haato": ["Gen 1", "Padoru X"],
  "hajime": ["ReGLOSS"],
  "iofi": ["AREA 15", "HoloIndonesia"],
  "iroha": ["holoX"],
  "irys": ["Promise"],
  "kaela": ["holoh3ro", "HoloIndonesia"],
  "kanade": ["ReGLOSS"],
  "kanata": ["holoForce", "holoWitches", "Kanata Construction", "Padoru Kanata"],
  "kobo": ["holoh3ro", "BoZet", "HoloIndonesia"],
  "korone": ["Dorobo Construction", "GAMERS", "Mikkorone", "OkaKoro"],
  "koyori": ["holoX", "SnowZnow"],
  "kronii": ["Promise", "KroMei"],
  "lamy": ["Easter Y", "NePoLaBo", "Padoru Lamy", "SnowZnow"],
  "laplus": ["Dorobo Construction", "holoX"],
  "lui": ["Dorobo Construction", "holoX", "HOLOTORI"],
  "luna": ["holoForce", "holoWitches", "SubaLuna"],
  "marine": ["Fantasy", "holoWitches", "MariFure", "PekoMari"],
  "matsuri": ["Gen 1"],
  "mel": ["Gen 1"],
  "miko": ["Gen 0", "Holowitches", "miComet", "Mikkorone", "Shiranui Construction", "Shiranui Constructions","FubuMiComet"],
  "mio": ["AyaFubuMi", "Dorobo Construction", "FubuMio", "GAMERS"],
  "mococo": ["Advent", "FUWAMOCO"],
  "moona": ["AREA 15", "Padoru Moona", "HoloIndonesia"],
  "mumei": ["Padoru Mumei", "Promise", "Shachimu", "FauMei", "preYdator", "HOLOTORI", "KroMei"],
  "nene": ["NePoLaBo"],
  "nerissa": ["Advent"],
  "niko": ["FLOW GLOW", "RioNiko"],
  "nodoka": ["Support"],
  "noel": ["Fantasy", "Shiranui Construction", "Shiranui Constructions"],
  "okayu": ["Dorobo Construction", "GAMERS", "OkaKoro"],
  "ollie": ["holoro", "HoloIndonesia"],
  "pekora": ["Fantasy", "PekoMari","PekoMama"],
  "polka": ["BAKATARE CIRCUS", "NePoLaBo", "Shiranui Construction", "Shiranui Constructions"],
  "raden": ["ReGLOSS"],
  "raora": ["Justice"],
  "reine": ["holoro", "HOLOTORI", "HoloIndonesia"],
  "riona": ["FLOW GLOW", "RioNiko"],
  "ririka": ["ReGLOSS"],
  "risu": ["AREA 15", "HoloIndonesia"],
  "roboco": ["Gen 0"],
  "shion": ["Gen 2", "holoWitches", "ManjiGumi"],
  "shiori": ["Advent"],
  "sora": ["Gen 0", "SorAZ"],
  "su": ["FLOW GLOW"],
  "subaru": ["Gen 2", "Padoru Subaru", "SubaLuna", "LambDuck", "Ui", "HOLOTORI"],
  "suisei": ["Easter O", "Gen 0", "miComet", "Padoru Suisei", "Shiranui Construction", "AS_tar", "FubuMiComet", "StartEnd"],
  "towa": ["holoForce", "Padoru Towa", "StartEnd"],
  "vivi": ["FLOW GLOW"],
  "watame": ["BAKATARE CIRCUS", "holoForce", "LambDuck"],
  "zeta": ["holoh3ro", "Padoru Zeta", "BoZet", "HoloIndonesia"],
  "Gen 1": ["Fubuki", "Matsuri", "Mel", "Haato", "Aki"],
  "kiara": ["HOLOTORI"],
};
