// config/imgExceptions.excel.js
// Auto-generated from 'Copy of Cards DB.xlsx' (Exceptions columns).
// Map: oshiId -> array of allowed card-name prefixes for /img (change-img.js).
module.exports = {
  "achan": ["Support"],
  "aki": ["Gen 1"],
  "anya": ["holoro"],
  "ao": ["ReGLOSS"],
  "ayame": ["AyaFubuMi", "Gen 2"],
  "azki": ["Easter X", "Gen 0", "Kanata Construction", "SorAZ"],
  "baelz": ["Promise"],
  "bijou": ["Advent"],
  "botan": ["NePoLaBo"],
  "cecilia": ["Justice"],
  "chihaya": ["FLOW GLOW"],
  "chloe": ["holoWitches", "holoX", "Kanata Construction", "Padoru Chloe", "Ruka"],
  "choco": ["Gen 2"],
  "elizabeth": ["Justice"],
  "fauna": ["Council", "Promise"],
  "flare": ["BAKATARE CIRCUS", "Fantasy", "MariFure", "Padoru Flare", "Shiranui Construction"],
  "fubuki": ["AyaFubuMi", "BAKATARE CIRCUS", "Dorobo Construction", "FubuMio", "GAMERS", "Gen 1"],
  "fuwawa": ["Advent", "FUWAMOCO"],
  "gigi": ["Justice"],
  "gura": ["Saba"],
  "haato": ["Gen 1", "Padoru X"],
  "hajime": ["ReGLOSS"],
  "iofi": ["AREA 15"],
  "iroha": ["holoX"],
  "irys": ["Promise"],
  "kaela": ["holoh3ro"],
  "kanade": ["ReGLOSS"],
  "kanata": ["holoForce", "holoWitches", "Kanata Construction", "Padoru Kanata"],
  "kobo": ["holoh3ro"],
  "korone": ["Dorobo Construction", "GAMERS", "Mikkorone", "OkaKoro"],
  "koyori": ["holoX"],
  "kronii": ["Promise"],
  "lamy": ["Easter Y", "NePoLaBo", "Padoru Lamy"],
  "laplus": ["Dorobo Construction", "holoX"],
  "lui": ["Dorobo Construction", "holoX"],
  "luna": ["holoForce", "holoWitches", "SubaLuna"],
  "marine": ["Fantasy", "holoWitches", "MariFure", "PekoMari"],
  "matsuri": ["Gen 1"],
  "mel": ["Gen 1"],
  "miko": ["Gen 0", "Holowitches", "miComet", "Mikkorone", "Shiranui Construction", "Shiranui Constructions"],
  "mio": ["AyaFubuMi", "Dorobo Construction", "FubuMio", "GAMERS"],
  "mococo": ["Advent", "FUWAMOCO"],
  "moona": ["AREA 15", "Padoru Moona"],
  "mumei": ["Padoru Mumei", "Promise"],
  "nene": ["NePoLaBo"],
  "nerissa": ["Advent"],
  "niko": ["FLOW GLOW"],
  "nodoka": ["Support"],
  "noel": ["Fantasy", "Shiranui Construction", "Shiranui Constructions"],
  "okayu": ["Dorobo Construction", "GAMERS", "OkaKoro"],
  "ollie": ["holoro"],
  "pekora": ["Fantasy", "PekoMari"],
  "polka": ["BAKATARE CIRCUS", "NePoLaBo", "Shiranui Construction", "Shiranui Constructions"],
  "raden": ["ReGLOSS"],
  "raora": ["Justice"],
  "reine": ["holoro"],
  "riona": ["FLOW GLOW"],
  "ririka": ["ReGLOSS"],
  "risu": ["AREA 15"],
  "roboco": ["Gen 0"],
  "shion": ["Gen 2", "holoWitches"],
  "shiori": ["Advent"],
  "sora": ["Gen 0", "SorAZ"],
  "su": ["FLOW GLOW"],
  "subaru": ["Gen 2", "Padoru Subaru", "SubaLuna"],
  "suisei": ["Easter O", "Gen 0", "miComet", "Padoru Suisei", "Shiranui Construction"],
  "towa": ["holoForce", "Padoru Towa"],
  "vivi": ["FLOW GLOW"],
  "watame": ["BAKATARE CIRCUS", "holoForce"],
  "zeta": ["holoh3ro", "Padoru Zeta"],
};
