
const { SlashCommandBuilder, EmbedBuilder, ActionRowBuilder, StringSelectMenuBuilder, ButtonBuilder, ButtonStyle, ComponentType } = require('discord.js');
const config=require('../../config.json'); const SummerUser=require('../../models/SummerUser'); const {SUMMER_CARDS,normalizeIsland}=require('../../config/summer-cards'); const {performSunPull}=require('../../utils/sunPull'); const {EVENT_NAME,EVENT_START_AT,EVENT_END_AT,getIslandChannelId,isSummerEventActive}=require('../../utils/summerEvent');
const A=require('../../utils/summerActivity'); const F=require('../../utils/summerFusion'); const S=require('../../utils/summerShop'); const {buildRewardPresentation}=require('../../utils/summerRewardMessage'); const {grantSummerWelcomeGift}=require('../../utils/summerWelcomeGift'); const {buildHolodoriImageUrl}=require('../../utils/holodoriLoginReward');
const LABEL={red:'Red Island',yellow:'Yellow Island',green:'Green Island',blue:'Blue Island'}, EMOJI={red:'🔴',yellow:'🟡',green:'🟢',blue:'🔵'};
function logo(e){const u=String(config.summerLogoUrl||'').trim();if(/^https?:\/\//i.test(u))e.setThumbnail(u);return e;} function members(i){return SUMMER_CARDS[i].join(', ');} function row(...c){return new ActionRowBuilder().addComponents(...c);} function btn(id,label,style=ButtonStyle.Secondary,disabled=false,emoji=null){const b=new ButtonBuilder().setCustomId(id).setLabel(label).setStyle(style).setDisabled(disabled);if(emoji)b.setEmoji(emoji);return b;}
function overview(){return logo(new EmbedBuilder().setTitle(`☀️ ${EVENT_NAME}`).setColor(0x00bbff).setDescription('Choose your permanent island for regular Summer pulls.').addFields(...Object.keys(LABEL).map(i=>({name:`${EMOJI[i]} ${LABEL[i]}`,value:members(i)}))).setFooter({text:`${EVENT_START_AT.toISOString()} to ${EVENT_END_AT.toISOString()}`}));}
function islandSelect(uid){return row(new StringSelectMenuBuilder().setCustomId(`summer:island:${uid}`).setPlaceholder('Choose your island').addOptions(Object.keys(LABEL).map(i=>({label:LABEL[i],value:i,emoji:EMOJI[i]}))));}
function confirm(uid,i){return row(btn(`summer:confirm:${i}:${uid}`,`Join ${LABEL[i]}`,ButtonStyle.Success),btn(`summer:back:${uid}`,'Go Back'));}
function hubEmbed(d){const i=normalizeIsland(d.island),day=A.getDayNumber(d);return logo(new EmbedBuilder().setTitle(`☀️ ${EVENT_NAME}`).setColor(0xf4c542).setDescription(`${EMOJI[i]} **${LABEL[i]}**\nRegular pulls: <#${getIslandChannelId(i)}>\n${isSummerEventActive()?'Event active':'Event outside scheduled dates'}${day?`\nActivity day: **${day}**`:''}`).addFields({name:'☀️ SUN Pulls',value:String(d.sunPulls||0),inline:true},{name:'🐚 Shells',value:String(d.summerShells||0),inline:true},{name:'🖼️ Full Arts fused',value:String(d.fusedFullArts?.length||0),inline:true}));}
function hubRows(uid,d){return [row(btn(`summer:sunpull:${uid}`,`Use SUN Pull (${d.sunPulls||0})`,ButtonStyle.Success,(d.sunPulls||0)<1,'☀️'),btn(`summer:activities:${uid}`,'Activities',ButtonStyle.Primary,false,'🏝️'),btn(`summer:fusion:${uid}`,'Full Art Fusion',ButtonStyle.Primary,false,'🖼️')),row(btn(`summer:shop:${uid}`,'Shell Shop',ButtonStyle.Primary,false,'🐚'),btn(`summer:refresh:${uid}`,'Refresh',ButtonStyle.Secondary,false,'🔄'),btn(`summer:info:${uid}`,'Event Info',ButtonStyle.Secondary,false,'ℹ️'))];}
async function showHub(interaction,uid){const gift=await grantSummerWelcomeGift(uid);const d=gift.summerUser||await SummerUser.findOne({userId:uid}).lean().exec();const content=gift.granted?`🎁 Welcome to ${LABEL[normalizeIsland(d.island)]}! You received **100 Summer Shells**.`:null;await interaction.editReply({content,embeds:[hubEmbed(d)],components:hubRows(uid,d)});}
function nextJstMidnightUnix(now=new Date()){const p=A.jstParts(now);return Math.floor(Date.UTC(Number(p.year),Number(p.month)-1,Number(p.day)+1,-9,0,0)/1000);}
function activityWindowStatus(d,day,w,now=new Date()){const s=A.getWindowState(d,day,w),label=w[0].toUpperCase()+w.slice(1);if(s.completed)return `✅ **${label}** — Completed`;if(s.coreId)return `▶️ **${label}** — In progress`;if(A.isWindowAvailable(d,w,now))return `▶️ **${label}** — Available now`;if(w==='noon')return `🔒 **${label}** — Complete Morning first`;if(w==='evening'){const morningDone=Boolean(A.getWindowState(d,day,'morning').completed);return `🔒 **${label}** — ${morningDone?'Complete Noon first':'Complete Morning and Noon first'}`;}return `🔒 **${label}**`; }
function activityHomeEmbed(d){const day=A.getDayNumber(d),data=A.getDayData(day),now=new Date();const lines=A.WINDOWS.map(w=>activityWindowStatus(d,day,w,now));return new EmbedBuilder().setTitle(`🏝️ Day ${day} Activities`).setColor(0x35c98b).setDescription(`${data?.chapter||''}
${data?.storyBeat||''}

${lines.join('\n')}

Daily reset: <t:${nextJstMidnightUnix(now)}:R>`);}
function activityHomeRows(uid,d){const day=A.getDayNumber(d);return [row(...A.WINDOWS.map(w=>{const s=A.getWindowState(d,day,w),disabled=!A.isWindowAvailable(d,w)||s.completed;return btn(`summer:window:${w}:${uid}`,w[0].toUpperCase()+w.slice(1),s.completed?ButtonStyle.Success:ButtonStyle.Primary,disabled);})),row(btn(`summer:hub:${uid}`,'Back to Summer Hub'))];}
function coreView(uid,d,w){const day=A.getDayNumber(d),win=A.getDayData(day)?.windows?.[w],state=A.getWindowState(d,day,w);if(!win)return {content:'No activity data exists for this time window.',embeds:[],components:[row(btn(`summer:activities:${uid}`,'Back'))]};if(state.coreId){const core=win.coreActivities.find(x=>x.id===state.coreId),step=core?.steps?.find(x=>x.id===state.stepId),options=A.getAvailableOptions(d,day,w,state.coreId,state.stepId);if(!core||!step)return {content:'This activity path is no longer valid. Please contact an administrator.',embeds:[],components:[row(btn(`summer:activities:${uid}`,'Back'))]};if(!options.length)return {content:'No choices are currently available for this path. Check the activity flag conditions.',embeds:[new EmbedBuilder().setTitle(core.buttonText).setDescription(`${state.lastResultDialogue||core.selectedDialogue}\n\n**${step.prompt}**`).setColor(0xe67e22)],components:[row(btn(`summer:activities:${uid}`,'Back'))]};return {content:null,embeds:[new EmbedBuilder().setTitle(core.buttonText).setDescription(`${state.lastResultDialogue||core.selectedDialogue}\n\n**${step.prompt}**`).setColor(0x35c98b)],components:[row(new StringSelectMenuBuilder().setCustomId(`summer:option:${w}:${core.id}:${step.id}:${uid}`).setPlaceholder('Choose an option').addOptions(options.map(o=>({label:o.text,value:o.id}))))]};}const cores=A.getAvailableCoreActivities(d,day,w);if(!cores.length)return {content:'No activities are available for your current story path in this window.',embeds:[new EmbedBuilder().setTitle(win.title||`${w} activities`).setDescription(win.openingDialogue).setColor(0xe67e22)],components:[row(btn(`summer:activities:${uid}`,'Back'))]};return {content:null,embeds:[new EmbedBuilder().setTitle(win.title||`${w} activities`).setDescription(win.openingDialogue).setColor(0x35c98b).addFields(...cores.map(c=>({name:c.buttonText||c.fullArtRoute,value:c.previewDialogue||c.fullArtRoute,inline:false})))],components:[row(...cores.map((c,i)=>btn(`summer:core:${w}:${c.id}:${uid}`,c.buttonText||c.fullArtRoute,[ButtonStyle.Primary,ButtonStyle.Success,ButtonStyle.Secondary][i%3]))),row(btn(`summer:activities:${uid}`,'Back'))]};}
function rewardEmbed(result){const r=result.reward;const reveal=buildRewardPresentation(r,{activity:result.core.buttonText||result.core.fullArtRoute,route:result.core.fullArtRoute});const completionDialogue=result.option?.completionDialogue||result.step?.completionDialogue||result.core?.completionDialogue;const story=[result.option?.resultDialogue,completionDialogue].filter(Boolean).join('\n\n');const rewardText=r.type==='bundle'?`**Rewards:**\n${reveal.rewardLabel.split('\n').map(x=>`• **${x}**`).join('\n')}`:`Reward: **${reveal.rewardLabel}**`;const description=[story,`**${reveal.message}**`,rewardText].filter(Boolean).join('\n\n');const e=new EmbedBuilder().setTitle(`${reveal.emoji} ${reveal.title}`).setColor(reveal.color).setDescription(description);const imageReward=r.type==='bundle'?(r.rewards||[]).find(x=>x.imageUrl):r;if(imageReward?.imageUrl)e.setImage(imageReward.imageUrl);return e;}
function shopEmbed(d){const first=!(d.holodoriFirstPurchaseClaimed===true);return new EmbedBuilder().setTitle('🐚 Summer Shell Shop').setColor(0xf4c542).setDescription(`Summer Shells: **${d.summerShells||0}**\n\nPurchase balances used by the existing pull commands.`).addFields({name:'🎟️ 1 Event Pull — 25 Shells',value:'A normal pull balance that does not refill with timed PullQuota.',inline:false},{name:'☀️ 1 SUN Pull — 50 Shells',value:'A guaranteed standard SUN card through the Summer menu.',inline:false},{name:'🎴 10 HOLODORI Pulls — 1,000 Shells',value:first?'Uses the daily rates. Your first purchase includes exactly one guaranteed normal ★★★★★ card from your selected island.':'All 10 cards use the daily rates: 85% ★★★, 10% ★★★★, 4% ★★★★★, 1% signed ★★★★★.',inline:false});}
function shopRows(uid,d){return [row(btn(`summer:shopselect:event_pull:${uid}`,'Buy Event Pull — 25',ButtonStyle.Primary,(d.summerShells||0)<25,'🎟️'),btn(`summer:shopselect:sun_pull:${uid}`,'Buy SUN Pull — 50',ButtonStyle.Success,(d.summerShells||0)<50,'☀️')),row(btn(`summer:shopselect:holodori_10:${uid}`,'10 HOLODORI — 1,000',ButtonStyle.Primary,(d.summerShells||0)<1000,'🎴')),row(btn(`summer:hub:${uid}`,'Back to Summer Hub'))];}
function shopConfirmEmbed(item,d){return new EmbedBuilder().setTitle('Confirm Purchase').setColor(0xf4c542).setDescription(`Buy **1 ${item.label}** for **${item.price} Summer Shells**?\n\nCurrent balance: **${d.summerShells||0} Shells**\nAfter purchase: **${Math.max(0,(d.summerShells||0)-item.price)} Shells**`);}
function shopConfirmRows(uid,itemId,token){return [row(btn(`summer:shopconfirm:${itemId}:${token}:${uid}`,'Confirm Purchase',ButtonStyle.Success,false,'✅'),btn(`summer:shop:${uid}`,'Cancel',ButtonStyle.Secondary,false,'✖️'))];}
function shopResultEmbed(result){const item=result.item;if(item.id==='holodori_10'){const guarantee=result.firstPurchase?`\n\n🎁 **First-purchase bonus:** One of these 10 cards is a guaranteed normal ★★★★★ from ${LABEL[result.island]}.`:'';return new EmbedBuilder().setTitle('✅ HOLODORI Purchase Complete').setColor(0x35c98b).setDescription(`You bought **10 HOLODORI Pulls** for **${item.price} Summer Shells**.\n\nSummer Shells remaining: **${result.remainingShells}**${guarantee}`);}const balanceText=item.id==='event_pull'?`Event Pulls: **${result.eventPulls}**`:`SUN Pulls: **${result.sunPulls}**`;return new EmbedBuilder().setTitle('✅ Purchase Complete').setColor(0x35c98b).setDescription(`You bought **1 ${item.label}** for **${item.price} Summer Shells**.\n\nSummer Shells remaining: **${result.remainingShells}**\n${balanceText}`);}
function holodoriCardEmbed(card,index,total,result){const image=buildHolodoriImageUrl(card,process.env.IMAGE_BASE||'http://152.69.195.48/images');const tags=[];if(card.signed)tags.push('SIGNED');if(card.islandGuaranteed)tags.push(`${LABEL[result.island]} guaranteed ★★★★★`);return new EmbedBuilder().setTitle(`[${card.rarity}] ${card.name}`).setColor(card.rarity==='★★★★★'?0xf4c542:card.rarity==='★★★★'?0xb19cd9:0x5ab3f4).setDescription(tags.length?`**${tags.join(' • ')}**`:null).setImage(image).setFooter({text:`HOLODORI card ${index+1}/${total}`});}
function holodoriResultRows(uid,index,total){return [row(btn(`summer:holoprev:${uid}`,'◀ Prev',ButtonStyle.Primary,total<=1),btn(`summer:holopage:${uid}`,`${index+1}/${total}`,ButtonStyle.Secondary,true),btn(`summer:holonext:${uid}`,'Next ▶',ButtonStyle.Primary,total<=1)),row(btn(`summer:shop:${uid}`,'Continue Shopping'),btn(`summer:hub:${uid}`,'Hub'))];}
function fusionMenu(uid){return row(new StringSelectMenuBuilder().setCustomId(`summer:fusionselect:${uid}`).setPlaceholder('Choose a Full Art recipe').addOptions(Object.keys(F.recipes).map(r=>({label:r,value:r,description:`Requires ${F.recipes[r].length} SUN cards`}))));}
function fusionEmbed(s){return new EmbedBuilder().setTitle(`🖼️ ${s.route} Full Art`).setColor(s.ready?0x35c98b:0xf4c542).setDescription(s.required.map(x=>`${x.ready?'✅':'❌'} ${x.name} — ${x.count}`).join('\n')+`\n\nFull Arts owned: **${s.ownedFullArt}**`).setImage(s.imageUrl);}
module.exports={data:new SlashCommandBuilder().setName('summer').setDescription('Open Hello! A Brand New Summer!'),requireOshi:true,async execute(interaction){await interaction.deferReply({ephemeral:true});const uid=interaction.user.id;let d=await SummerUser.findOne({userId:uid}).lean().exec();let activeHolodoriResult=null;let activeHolodoriPage=0;if(d?.island)await showHub(interaction,uid);else await interaction.editReply({embeds:[overview()],components:[islandSelect(uid)]});const msg=await interaction.fetchReply();const col=msg.createMessageComponentCollector({time:10*60*1000,filter:c=>c.user.id===uid&&c.customId.endsWith(`:${uid}`)});col.on('collect',async c=>{try{
 if(c.componentType===ComponentType.StringSelect&&c.customId.startsWith('summer:island:')){const i=normalizeIsland(c.values[0]);return c.update({embeds:[new EmbedBuilder().setTitle(`Confirm ${LABEL[i]}`).setDescription('This choice is permanent for the event.').addFields({name:'Members',value:members(i)})],components:[confirm(uid,i)]});}
 if(c.customId===`summer:back:${uid}`)return c.update({embeds:[overview()],components:[islandSelect(uid)]});
 if(c.customId.startsWith('summer:confirm:')){await c.deferUpdate();const i=normalizeIsland(c.customId.split(':')[2]);await SummerUser.updateOne({userId:uid},{$setOnInsert:{userId:uid,island:i}},{upsert:true,setDefaultsOnInsert:true});await SummerUser.updateOne({userId:uid,island:null},{$set:{island:i}});return showHub(interaction,uid);}
 if(c.customId===`summer:hub:${uid}`||c.customId===`summer:refresh:${uid}`){await c.deferUpdate();return showHub(interaction,uid);}
 if(c.customId===`summer:shop:${uid}`){await c.deferUpdate();d=await SummerUser.findOne({userId:uid}).lean();return interaction.editReply({content:null,embeds:[shopEmbed(d)],components:shopRows(uid,d)});}
 if(c.customId.startsWith('summer:shopselect:')){await c.deferUpdate();const itemId=c.customId.split(':')[2],item=S.getShopItem(itemId);if(!item)return interaction.editReply({content:'That shop item does not exist.',embeds:[],components:[row(btn(`summer:shop:${uid}`,'Back'))]});d=await SummerUser.findOne({userId:uid}).lean();if((d.summerShells||0)<item.price)return interaction.editReply({content:`You need ${item.price} Summer Shells, but only have ${d.summerShells||0}.`,embeds:[],components:[row(btn(`summer:shop:${uid}`,'Back to Shop'))]});const token=S.createPurchaseToken();return interaction.editReply({content:null,embeds:[shopConfirmEmbed(item,d)],components:shopConfirmRows(uid,itemId,token)});}
 if(c.customId.startsWith('summer:shopconfirm:')){await c.deferUpdate();const parts=c.customId.split(':'),itemId=parts[2],token=parts[3];const result=await S.purchaseShopItem(uid,itemId,token);if(!result.success){let message='Purchase failed.';if(result.reason==='NOT_ENOUGH_SHELLS')message=`You do not have enough Summer Shells. Current balance: ${result.balance||0}.`;if(result.reason==='ALREADY_PROCESSED')message='This purchase was already processed.';if(result.reason==='NO_SUMMER_USER')message='Your Summer profile could not be found.';return interaction.editReply({content:message,embeds:[],components:[row(btn(`summer:shop:${uid}`,'Back to Shop'),btn(`summer:hub:${uid}`,'Hub'))]});}if(result.item.id==='holodori_10'){activeHolodoriResult=result;activeHolodoriPage=0;return interaction.editReply({content:null,embeds:[shopResultEmbed(result),holodoriCardEmbed(result.cards[0],0,result.cards.length,result)],components:holodoriResultRows(uid,0,result.cards.length)});}return interaction.editReply({content:null,embeds:[shopResultEmbed(result)],components:[row(btn(`summer:shop:${uid}`,'Continue Shopping'),btn(`summer:hub:${uid}`,'Hub'))]});}
 if(c.customId===`summer:holoprev:${uid}`||c.customId===`summer:holonext:${uid}`){if(!activeHolodoriResult?.cards?.length)return c.update({content:'This HOLODORI result is no longer available.',embeds:[],components:[row(btn(`summer:shop:${uid}`,'Back to Shop'))]});activeHolodoriPage=c.customId.includes('holoprev')?(activeHolodoriPage-1+activeHolodoriResult.cards.length)%activeHolodoriResult.cards.length:(activeHolodoriPage+1)%activeHolodoriResult.cards.length;return c.update({content:null,embeds:[shopResultEmbed(activeHolodoriResult),holodoriCardEmbed(activeHolodoriResult.cards[activeHolodoriPage],activeHolodoriPage,activeHolodoriResult.cards.length,activeHolodoriResult)],components:holodoriResultRows(uid,activeHolodoriPage,activeHolodoriResult.cards.length)});}
 if(c.customId===`summer:info:${uid}`)return c.update({embeds:[new EmbedBuilder().setTitle('Summer Event Info').setDescription('Choose one of three core activities in each time window. Your VN choices determine which member SUN cards can appear if the activity reward rolls a SUN card. Full Arts are fused from complete member sets.')],components:[row(btn(`summer:hub:${uid}`,'Back'))]});
 if(c.customId===`summer:sunpull:${uid}`){await c.deferUpdate();const r=await performSunPull(uid);if(!r.success)return interaction.editReply({content:r.reason==='NO_PULLS'?'No SUN Pulls available.':'SUN Pull failed.',components:[row(btn(`summer:hub:${uid}`,'Back'))]});const e=new EmbedBuilder().setTitle(`☀️ [SUN] ${r.card.cardName}`).setDescription(`SUN Pulls remaining: **${r.remainingSunPulls}**`).setImage(r.card.imageUrl);return interaction.editReply({content:null,embeds:[e],components:[row(btn(`summer:hub:${uid}`,'Back'))]});}
 if(c.customId===`summer:activities:${uid}`){await c.deferUpdate();d=await SummerUser.findOne({userId:uid}).lean();const day=A.getDayNumber(d);if(!day)return interaction.editReply({content:'No August activity day is active.',embeds:[],components:[row(btn(`summer:hub:${uid}`,'Back'))]});return interaction.editReply({content:null,embeds:[activityHomeEmbed(d)],components:activityHomeRows(uid,d)});}
 if(c.customId.startsWith('summer:window:')){await c.deferUpdate();const w=c.customId.split(':')[2];d=await SummerUser.findOne({userId:uid}).lean();return interaction.editReply(coreView(uid,d,w));}
 if(c.customId.startsWith('summer:core:')){await c.deferUpdate();const [, ,w,coreId]=c.customId.split(':');d=await SummerUser.findOne({userId:uid}).lean();const day=A.getDayNumber(d);const r=await A.selectCore(uid,day,w,coreId);if(!r.success){const message=r.reason==='CONDITION_FAILED'?'That activity is not available on your current story path.':r.reason==='NO_AVAILABLE_STEPS'?'That activity has no valid starting step for your current story flags.':'That activity is already locked or completed.';return interaction.editReply({content:message,embeds:[],components:[row(btn(`summer:activities:${uid}`,'Back'))]});}d=await SummerUser.findOne({userId:uid}).lean();return interaction.editReply(coreView(uid,d,w));}
 if(c.componentType===ComponentType.StringSelect&&c.customId.startsWith('summer:option:')){await c.deferUpdate();const parts=c.customId.split(':'),w=parts[2],coreId=parts[3],stepId=parts[4];d=await SummerUser.findOne({userId:uid}).lean();const day=A.getDayNumber(d);const r=await A.chooseOption(uid,day,w,coreId,stepId,c.values[0]);if(!r.success){let message='This choice is no longer available.';if(r.reason==='CONDITION_FAILED')message='Your story flags no longer allow that choice.';if(r.reason==='NEXT_STEP_CONDITION_FAILED')message=`The selected choice points to ${r.nextStepId}, but that step's flag conditions are not satisfied.`;return interaction.editReply({content:message,embeds:[],components:[row(btn(`summer:activities:${uid}`,'Back'))]});}if(r.completed)return interaction.editReply({content:null,embeds:[rewardEmbed(r)],components:[row(btn(`summer:activities:${uid}`,'Activities'),btn(`summer:hub:${uid}`,'Hub'))]});d=await SummerUser.findOne({userId:uid}).lean();return interaction.editReply(coreView(uid,d,w));}
 if(c.customId===`summer:fusion:${uid}`)return c.update({embeds:[new EmbedBuilder().setTitle('🖼️ Full Art Fusion').setDescription('Choose a recipe to view your progress.')],components:[fusionMenu(uid),row(btn(`summer:hub:${uid}`,'Back'))]});
 if(c.componentType===ComponentType.StringSelect&&c.customId===`summer:fusionselect:${uid}`){const route=c.values[0],s=await F.getFusionStatus(uid,route);return c.update({embeds:[fusionEmbed(s)],components:[row(btn(`summer:fuse:${encodeURIComponent(route)}:${uid}`,'Fuse Full Art',ButtonStyle.Success,!s.ready),btn(`summer:fusion:${uid}`,'Back'))]});}
 if(c.customId.startsWith('summer:fuse:')){await c.deferUpdate();const route=decodeURIComponent(c.customId.split(':')[2]),r=await F.fuseFullArt(uid,route);if(!r.success)return interaction.editReply({content:'You are missing one or more required SUN cards.',embeds:r.status?[fusionEmbed(r.status)]:[],components:[row(btn(`summer:fusion:${uid}`,'Back'))]});return interaction.editReply({content:null,embeds:[new EmbedBuilder().setTitle(`🖼️ ${route} Full Art Created!`).setImage(r.imageUrl).setColor(0xf4c542)],components:[row(btn(`summer:fusion:${uid}`,'More Recipes'),btn(`summer:hub:${uid}`,'Hub'))]});}
 }catch(e){console.error('[summer]',e);if(!c.deferred&&!c.replied)await c.reply({content:'Summer event error.',ephemeral:true}).catch(()=>{});}});}};
